import fs from 'fs';

const SERVER_FILE = 'server/server.js';

// ─── Leer server.js ───
const content = fs.readFileSync(SERVER_FILE, 'utf8');
const lines = content.split('\n');

// ─── Identificar TODOS los route blocks y las variables no-locales que usan ───
const routes = [];
let i = 0;
while (i < lines.length) {
  const match = lines[i].match(/^(app\.(get|post|put|delete|use)\()/);
  if (match) {
    const startLine = i;
    const routeMatch = lines[i].match(/app\.(get|post|put|delete|use)\(([^,]+),\s*/);
    const method = match[2];
    
    // Find the end of the route (matching brackets)
    let depth = 0;
    let j = i;
    let inRoute = false;
    let routeEnd = i;
    
    // Count brackets to find where this route handler ends
    for (let k = i; k < lines.length; k++) {
      const line = lines[k];
      if (k === i) {
        // First line: app.method('/path', ...) - find the opening brace of the callback
        const braceIdx = line.indexOf('=> {');
        if (braceIdx === -1) continue; // skip non-arrow-function routes (like app.use)
        inRoute = true;
        depth = 1; // the opening { after =>
        continue;
      }
      if (!inRoute) continue;
      
      for (const ch of line) {
        if (ch === '{' || ch === '(' || ch === '[') depth++;
        if (ch === '}' || ch === ')' || ch === ']') depth--;
      }
      
      if (depth <= 0 && line.includes('});')) {
        // Check it's really the end - the }); should close the handler
        // Look for pattern: });  or  });\r
        if (/}\s*\)\s*;\s*$/.test(line.trim()) || line.trim() === '});') {
          routeEnd = k;
          break;
        }
        // Reset depth if }); wasn't the end
        depth = 1;
      }
    }
    
    if (routeEnd > i) {
      routes.push({
        startLine,
        endLine: routeEnd,
        method,
        text: lines.slice(startLine, routeEnd + 1).join('\n')
      });
      i = routeEnd + 1;
      continue;
    }
  }
  i++;
}

console.log(`Found ${routes.length} route definitions`);
console.log(`Route lines: ${routes.map(r => `${r.startLine+1}-${r.endLine+1} (${r.method})`).join(', ')}`);

// ─── Save route list for later processing ───
fs.writeFileSync('server/_routes_data.json', JSON.stringify(routes, null, 2));
console.log('Saved route data to server/_routes_data.json');

// ─── Now extract ALL closure variables used across all routes ───
const CLOSURE_VARS = new Set();
const RESERVED = new Set([
  'req','res','async','await','try','catch','const','let','var','new','return',
  'if','else','for','of','in','true','false','null','undefined','this','throw',
  'typeof','instanceof','console','path','fs','Error','Promise','Array','Object',
  'String','Number','Boolean','Date','RegExp','Math','JSON','Buffer','setTimeout',
  'setInterval','clearTimeout','clearInterval','process','Buffer','Int8Array',
  'Int16Array','Int32Array','Uint8Array','Uint16Array','Uint32Array','Float32Array',
  'Float64Array','Map','Set','WeakMap','WeakSet','Symbol','BigInt','parseInt',
  'parseFloat','isNaN','isFinite','decodeURI','decodeURIComponent','encodeURI',
  'encodeURIComponent','global','globalThis','module','exports','require',
  '__dirname','__filename','import','from','export','default','class','super',
  'extends','static','get','set','function','switch','case','break','do','while',
  'with','debugger','delete','void','yield','await','async','type','typeof',
  'instanceof','implements','interface','package','private','protected','public',
  'static','arguments','constructor','hasOwnProperty','prototype','toString',
  'valueOf','toLocaleString','isPrototypeOf','propertyIsEnumerable',
  'than','the','this','that','have','has','had','not','but','for','are','all',
  'any','can','every','may','some','which','who','whom','what','when','where',
  'why','how','much','many','few','several','each','both','neither','either',
  'below','above','across','against','along','among','around','at','before',
  'behind','beside','between','beyond','by','down','during','except','from',
  'inside','into','near','off','on','out','outside','over','since','through',
  'throughout','to','toward','under','until','up','upon','with','within','without',
  'abort','about','above','absent','accept','according','across','act','actually',
  'added','addition','adjust','after','again','against','agree','ahead','allow',
  'allowed','along','already','also','although','among','amount','an','and',
  'another','answer','any','anybody','anyone','anything','anyway','apart',
  'appear','appeared','appears','apply','approach','appropriate','approximately',
  'are','area','argue','arise','around','arrange','arrangement','arrive','article',
  'aside','ask','associated','assume','at','attach','attack','attempt','attend',
  'attract','authority','available','average','avoid','award','aware','away',
  'back','bad','base','based','basic','basis','bear','beat','beauty','became',
  'because','become','becoming','bed','been','before','begin','beginning','behalf',
  'behave','behavior','behind','being','belief','believe','bell','belong','below',
  'beneath','beside','besides','best','better','between','beyond','bit','bite',
  'black','block','blood','blow','blue','board','body','bone','book','border',
  'born','both','bottle','bottom','bound','bowl','branch','bread','break','breath',
  'bridge','brief','bright','bring','broken','brother','brown','brush','budget',
  'build','bunch','burden','burn','burst','bus','busy','butter','button','buy',
  'buyer','call','camera','camp','campaign','can','cancel','capable','capacity',
  'capital','capture','carbon','care','career','careful','carry','case','cash',
  'cast','catch','category','cattle','cause','celebrate','cell','cent','center',
  'central','century','ceremony','certain','certainly','chain','chair','challenge',
  'chamber','champion','championship','chance','change','changing','channel',
  'chapter','character','characteristic','charge','cheap','check','chemical',
  'chief','child','childhood','chip','choice','choose','church','circle','circumstance',
  'citizen','city','civil','claim','class','classic','classroom','clean','clear',
  'clearly','climb','close','closed','closely','closer','closest','closing','club',
  'cluster','coal','coast','code','coffee','cognitive','cold','collapse','colleague',
  'collect','collection','college','color','column','combination','combine','come',
  'comfort','comfortable','coming','command','comment','commercial','commission',
  'commit','commitment','committee','common','commonly','communicate','communication',
  'community','company','compare','comparison','compete','competition','competitive',
  'competitor','complain','complaint','complete','completely','complex','complicate',
  'component','compose','composition','comprehensive','computer','concentrate',
  'concentration','concept','conception','concern','concerned','conclude',
  'conclusion','concrete','condition','conduct','conference','confidence','confident',
  'confirm','conflict','confuse','confusion','congress','connect','connection',
  'conscious','consciousness','consequence','consequently','conservation',
  'conservative','consider','considerable','consideration','consist','consistent',
  'constant','constantly','constitute','constitutional','construct','construction',
  'consultant','consume','consumer','consumption','contact','contain','container',
  'contemporary','content','contest','context','continent','continue','continued',
  'contract','contrast','contribute','contribution','control','controversial',
  'controversy','convention','conventional','conversation','conversion','convert',
  'convince','convinced','cook','cookie','cooking','cool','cooperate','cooperation',
  'cope','copy','core','corner','corporate','correct','correctly','cost','cotton',
  'council','count','counter','country','county','couple','courage','course',
  'court','cousin','cover','coverage','crack','craft','crash','crazy','cream',
  'create','creation','creative','creativity','creature','credit','crew','crime',
  'criminal','crisis','criteria','criterion','critical','criticism','crop',
  'cross','crowd','crucial','cultural','culture','cup','cure','curious','current',
  'currently','curriculum','custom','customer','cut','cycle','dad','daily','damage',
  'dance','danger','dangerous','dare','dark','darkness','data','database','date',
  'daughter','day','dead','deal','dealer','dear','death','debate','debt','decade',
  'decide','decision','decision-making','deck','declare','decline','decrease',
  'deep','deeply','deer','default','defeat','defend','defendant','defense',
  'defensive','deficit','define','definitely','definition','degree','delay',
  'deliberately','deliver','delivery','demand','democracy','Democrat','democratic',
  'demonstrate','demonstration','deny','department','depend','dependent','depending',
  'depict','deposit','depression','depth','deputy','derive','describe','description',
  'desert','deserve','design','designer','desire','desk','desperate','despite',
  'destroy','destruction','detail','detailed','detect','determination','determine',
  'determined','develop','developing','development','device','devote','dialogue',
  'die','diet','differ','difference','different','differently','difficult',
  'difficulty','dig','digital','dimension','dinner','direct','direction','directly',
  'director','dirt','dirty','disable','disadvantage','disagree','disappear',
  'disaster','discipline','discount','discourage','discover','discovery',
  'discrimination','discuss','discussion','disease','dismiss','display','dispute',
  'distance','distant','distinct','distinction','distinguish','distribute',
  'distribution','district','diverse','diversity','divide','division','doctor',
  'document','dog','domestic','dominant','dominate','door','double','doubt',
  'down','downtown','dozen','draft','drag','drama','dramatic','dramatically',
  'draw','drawing','dream','dress','drink','drive','driver','drop','drug','dry',
  'due','during','dust','duty','dynamic','each','eager','ear','early','earn',
  'earnings','earth','ease','easily','east','eastern','easy','eat','economic',
  'economics','economist','economy','edge','edition','editor','educate','education',
  'educational','educator','effect','effective','effectively','efficiency',
  'efficient','effort','egg','eight','either','elbow','elderly','elect','election',
  'electric','electricity','electronic','element','elevator','eleven','eligible',
  'eliminate','elite','else','elsewhere','emerge','emergence','emergency',
  'emission','emotion','emotional','emphasis','emphasize','empire','empirical',
  'employ','employee','employer','employment','empty','enable','encounter',
  'encourage','encouraging','end','ending','endless','endorse','endorsement',
  'endure','enemy','energy','enforce','enforcement','engage','engagement','engine',
  'engineer','engineering','enjoy','enormous','enough','ensure','enter','enterprise',
  'entertainment','enthusiasm','enthusiast','entire','entirely','entitle',
  'entrepreneur','entry','environment','environmental','episode','equal','equally',
  'equipment','era','error','escape','especially','essay','essential','essentially',
  'establish','establishment','estate','estimate','estimate','etc','ethical',
  'ethnic','evaluate','evaluation','even','evening','event','eventually','ever',
  'every','everybody','everyday','everyone','everything','everywhere','evidence',
  'evolution','evolve','exact','exactly','examination','examine','example',
  'exceed','excellent','exception','excessive','exchange','excited','excitement',
  'exciting','exclude','exclusive','exclusively','excuse','execute','execution',
  'executive','exercise','exhibit','exhibition','exist','existence','existing',
  'expand','expansion','expect','expectation','expense','expensive','experience',
  'experiment','experimental','expert','expertise','explain','explanation',
  'explicit','explicitly','exploit','exploration','explore','explosion','export',
  'expose','exposure','express','expression','extend','extension','extensive',
  'extent','external','extra','extraordinary','extreme','extremely','eye','fabric',
  'face','facilitate','facility','fact','factor','factory','faculty','fade',
  'fail','failure','fair','fairly','fairness','faith','fall','false','familiar',
  'family','famous','fan','fantasy','far','farm','farmer','fashion','fast','fat',
  'fate','father','fault','favor','favorable','favorite','fear','feature',
  'federal','fee','feed','feedback','feel','feeling','fellow','female','fence',
  'few','fewer','fiber','fiction','field','fifteen','fifty','fight','fighter',
  'fighting','figure','file','fill','film','final','finally','finance','financial',
  'find','finding','fine','finger','finish','fire','firm','first','fish','fishing',
  'fit','fitness','five','fix','flag','flame','flat','flee','flesh','flexibility',
  'flexible','flight','float','flood','floor','flow','flower','fly','focus',
  'folk','follow','following','food','foot','football','force','foreign','forest',
  'forever','forget','form','formal','format','formation','former','formula',
  'forth','fortune','forward','found','foundation','founder','four','fourth',
  'frame','framework','free','freedom','freeze','frequency','frequently','fresh',
  'friend','friendly','friendship','front','frozen','fruit','frustration','fuel',
  'full','fully','fun','function','fund','fundamental','funding','funeral',
  'funny','furniture','furthermore','gain','galaxy','gallery','game','gang','gap',
  'garage','garden','gas','gate','gather','gathering','gay','gaze','gear','gender',
  'gene','general','generally','generate','generation','generic','generous',
  'genetic','gentle','gentleman','genuine','gesture','giant','gift','gift',
  'girl','give','given','glad','glance','glass','global','glove','go','goal',
  'god','gold','golden','golf','gone','good','govern','government','governor',
  'grab','grade','gradually','graduate','grain','grand','grandfather','grandmother',
  'grant','grass','grateful','grave','gray','great','greatest','green','greet',
  'grew','ground','group','grow','growing','growth','guarantee','guard','guess',
  'guest','guide','guideline','guilty','gun','gut','guy','habit','habitat','hair',
  'half','hall','hand','handful','handle','handling','hang','happen','happening',
  'happiness','happy','harbor','hard','hardly','harm','harmful','hat','hate',
  'haunting','head','headline','headquarters','heal','health','healthy','hear',
  'hearing','heart','heat','heating','heaven','heavily','heavy','heel','height',
  'helicopter','hell','hello','help','helpful','hence','herb','here','heritage',
  'hero','herself','hidden','hide','high','highlight','highly','highway','hill',
  'himself','hip','hire','his','historian','historic','historical','history',
  'hit','hobby','hold','holder','holding','hole','holiday','hollow','holy','home',
  'honest','honestly','honor','hook','hope','hopeful','hopefully','horizon',
  'horn','horror','horse','hospital','host','hotel','hour','house','household',
  'housing','huge','human','humor','hundred','hunter','hunting','hurt','husband',
  'hypothesis','ice','ice','idea','ideal','identification','identify','identity',
  'ideological','ideology','ignore','ill','illegal','illness','illusion',
  'illustrate','image','imagination','imaginative','imagine','immediate',
  'immediately','immense','immigrant','immigration','immune','impact','implement',
  'implementation','implication','implicit','imply','importance','important',
  'impose','impossible','impress','impression','impressive','improve','improvement',
  'impulse','incentive','inch','incident','include','including','income',
  'incorporate','increase','increased','increasing','increasingly','incredible',
  'indeed','independence','independent','index','indicate','indication','indicator',
  'individual','industrial','industry','inevitable','inevitably','infant',
  'infection','inflation','influence','influential','inform','informal',
  'information','infrastructure','ingredient','inherent','initial','initially',
  'initiate','initiative','injure','injury','inner','innocent','innovation',
  'innovative','input','inquiry','insect','inside','insight','insist','inspect',
  'inspiration','inspire','install','installation','instance','instant','instead',
  'institution','institutional','instruction','instructor','instrument',
  'insurance','intact','integrate','integration','integrity','intellectual',
  'intelligence','intelligent','intend','intense','intensity','intention',
  'interaction','interest','interested','interesting','interests','interfere',
  'interior','internal','international','internet','interpret','interpretation',
  'intervention','interview','intimate','into','introduce','introduction',
  'invade','invasion','invent','invention','invest','investigate','investigation',
  'investigator','investment','investor','invisible','invitation','invite',
  'involve','involved','involvement','iron','ironic','irony','island','isolate',
  'isolation','issue','item','its','itself','jacket','jail','jet','jewelry',
  'job','join','joint','joke','journal','journalist','journey','joy','judge',
  'judgment','juice','jump','junction','junior','jurisdiction','jury','justice',
  'justify','keen','keep','key','kick','kid','kill','killer','killing','kind',
  'king','kiss','kitchen','knee','knife','knock','know','knowledge','label',
  'labor','laboratory','lack','ladder','lady','lake','land','landing','landmark',
  'landscape','lane','language','lap','large','largely','last','late','later',
  'latest','latter','laugh','launch','law','lawn','lawsuit','lawyer','lay','layer',
  'layout','lazy','lead','leader','leadership','leading','leaf','league','lean',
  'leap','learn','learning','least','leather','leave','lecture','left','leg',
  'legacy','legal','legend','legislation','legitimate','lemon','lend','length',
  'lens','less','lesson','let','letter','level','liberal','library','license',
  'lick','lie','life','lifestyle','lifetime','lift','light','like','likely',
  'limit','limitation','limited','line','link','lion','lip','liquid','list',
  'listen','listener','literally','literary','literature','little','live','liver',
  'living','load','loan','lobby','local','locate','location','lock','log',
  'logic','logical','long','look','loop','loose','lord','lose','loss','lost',
  'lot','lots','loud','love','lovely','lover','low','lower','luck','lucky',
  'lunch','lung','machine','mad','magazine','magic','magnetic','magnificent',
  'main','mainly','maintain','maintenance','major','majority','make','maker',
  'makeup','male','mall','manage','management','manager','manner','manufacturer',
  'manufacturing','many','map','margin','mark','market','marketing','marketplace',
  'marriage','married','marry','mask','mass','massive','master','match','mate',
  'material','math','matter','mature','maximum','may','maybe','mayor','meal',
  'mean','meaning','means','meantime','meanwhile','measure','measurement','meat',
  'mechanic','mechanical','mechanism','medal','media','medical','medication',
  'medicine','medium','meet','meeting','member','membership','memory','mental',
  'mention','menu','merchant','mercy','mere','merely','merge','merger','merit',
  'message','metal','method','methodology','middle','midnight','might','mild',
  'mile','military','milk','mill','mind','mine','mineral','minimal','minimize',
  'minimum','minister','minor','minority','minute','miracle','mirror','miserable',
  'mislead','miss','missile','missing','mission','mistake','mix','mixed','mixture',
  'mobile','mode','model','moderate','modern','modest','modify','mom','moment',
  'momentum','money','monitor','month','mood','moon','moral','more','moreover',
  'morning','mortgage','most','mostly','mother','motion','motivate','motivation',
  'motor','mount','mountain','mouse','mouth','move','movement','movie','much',
  'multiple','multiply','municipal','murder','muscle','museum','music','musical',
  'musician','mutual','my','myself','mysterious','mystery','myth','nail','naked',
  'name','narrative','narrow','nation','national','native','natural','naturally',
  'nature','navy','near','nearby','nearly','necessarily','necessary','neck',
  'need','negative','neglect','negotiate','negotiation','neighbor','neighborhood',
  'neither','nerve','nervous','nest','net','network','neutral','never',
  'nevertheless','new','newly','news','newspaper','next','nice','night','nine',
  'nobody','nod','noise','nomination','none','nonetheless','nonsense','noon',
  'nor','norm','normal','normally','north','northern','nose','note','notebook',
  'nothing','notice','notion','novel','now','nowhere','nuclear','number',
  'numerous','nurse','nut','object','objective','obligation','observation',
  'observe','observer','obtain','obvious','obviously','occasion','occasionally',
  'occupation','occupy','occur','ocean','odd','odds','off','offense','offensive',
  'offer','office','officer','official','often','oil','ok','old','olympic',
  'omit','once','ongoing','onion','online','only','onto','open','opening',
  'operate','operating','operation','operator','opinion','opponent','opportunity',
  'oppose','opposite','opposition','option','optional','orange','orbit','order',
  'ordinary','organ','organic','organization','organize','organizer','orientation',
  'origin','original','originally','otherwise','ought','our','ours','ourselves',
  'outcome','outdoor','outer','outlet','outline','output','outside','outstanding',
  'overall','overcome','overlook','overnight','overseas','overview','overwhelm',
  'owe','own','owner','ownership','oxygen','pace','pack','package','page','paid',
  'pain','painful','paint','painter','painting','pair','pale','palm','panel',
  'panic','paper','paradigm','paragraph','parallel','parameter','parent','parental',
  'park','parking','part','participant','participate','participation','particular',
  'particularly','partly','partner','partnership','party','pass','passage',
  'passenger','passing','passion','past','path','patience','patient','pattern',
  'pause','pay','payment','peace','peak','peer','penalty','pending','penetrate',
  'pension','people','per','perceive','perception','perfect','perfectly','perform',
  'performance','perhaps','period','permanent','permission','permit','person',
  'personal','personality','personally','personnel','perspective','persuade',
  'pet','phase','phenomenon','philosophy','phone','photo','photograph','photographer',
  'phrase','physical','physically','physician','physics','piano','pick','picture',
  'piece','pile','pilot','pine','pink','pipe','pitch','place','plain','plan',
  'plane','planet','planning','plant','plastic','plate','platform','play','player',
  'plea','pleasant','please','pleased','pleasure','plenty','plot','plus','pocket',
  'poem','poet','poetry','point','pole','police','policy','political','politically',
  'politician','politics','poll','pollution','pool','poor','pop','popular',
  'popularity','population','pork','port','portfolio','portion','portrait','pose',
  'position','positive','possess','possession','possibility','possible','possibly',
  'post','poster','pot','potato','potential','potentially','pound','pour','poverty',
  'powder','power','powerful','practical','practice','pray','prayer','preceding',
  'precious','precise','precisely','predict','prediction','prefer','preference',
  'pregnancy','pregnant','preliminary','premise','premium','preparation','prepare',
  'prepared','presence','present','presentation','preserve','presidency','president',
  'presidential','press','pressure','presumably','pretend','pretty','prevail',
  'prevent','prevention','previous','previously','price','pride','priest','primarily',
  'primary','prime','principal','principle','print','prior','priority','prison',
  'prisoner','privacy','private','privately','privilege','prize','probably',
  'problem','procedure','proceed','process','produce','producer','product',
  'production','profession','professional','professor','profile','profit',
  'program','programming','progress','project','prominent','promise','promising',
  'promote','promotion','prompt','proof','proper','properly','property','proportion',
  'proposal','propose','proposed','prosecutor','prospect','protect','protection',
  'protective','protein','protest','proud','prove','provide','provider','province',
  'provision','psychological','psychologist','psychology','public','publication',
  'publicity','publish','published','publisher','pull','punishment','purchase',
  'pure','purpose','pursue','pursuit','push','qualify','quality','quarter',
  'quarterback','question','quick','quickly','quiet','quietly','quit','quite',
  'quote','race','racial','radical','radio','rail','rain','raise','range','rank',
  'rapid','rapidly','rare','rarely','rate','rather','rating','ratio','raw','reach',
  'react','reaction','read','reader','reading','ready','real','realistic','reality',
  'realize','really','realm','reason','reasonable','reasoning','recall','receive',
  'recent','recently','recipe','recognition','recognize','recommend',
  'recommendation','record','recording','recover','recovery','recruit','red',
  'reduce','reduction','refer','reference','reflect','reflection','reform','refugee',
  'refuse','regard','regarding','regardless','regime','region','regional','register',
  'registration','regret','regular','regularly','regulate','regulation','regulator',
  'reinforce','reject','relate','relation','relationship','relative','relatively',
  'relax','release','relevant','relief','religion','religious','reluctant','rely',
  'remain','remaining','remarkable','remember','remind','remote','remove','repeat',
  'repeatedly','replace','replacement','reply','report','reporter','represent',
  'representation','representative','republic','reputation','request','require',
  'requirement','research','researcher','resemble','reservation','reserve',
  'residence','resident','residential','resign','resist','resistance','resolution',
  'resolve','resort','resource','respond','response','responsibility','responsible',
  'rest','restaurant','restore','restriction','result','resume','retail','retain',
  'retire','retirement','retreat','return','reveal','revenue','reverse','review',
  'revolution','revolutionary','reward','rhetoric','rhythm','rich','rid','ride',
  'rifle','right','ring','riot','rise','risk','risky','ritual','rival','river',
  'road','rob','rock','rod','role','roll','romantic','roof','room','root','rope',
  'rose','rough','roughly','round','route','routine','row','royal','rub','rule',
  'run','runner','running','rural','rush','sacred','sad','safe','safety','sake',
  'salad','salary','sale','sales','salt','same','sample','sanction','sand',
  'satellite','satisfaction','satisfy','sauce','save','saving','savings','scale',
  'scandal','scared','scatter','scenario','scene','schedule','scheme','scholar',
  'scholarship','school','science','scientific','scientist','scope','score',
  'scream','screen','script','sculpture','sea','search','season','seat','second',
  'secret','secretary','section','sector','secure','security','see','seed','seek',
  'segment','seize','select','selection','self','sell','senate','senator','send',
  'senior','sense','sensitive','sensitivity','sentence','sentiment','separate',
  'separation','sequence','series','serious','seriously','servant','serve',
  'service','session','set','setting','settle','settlement','setup','seven',
  'several','severe','sex','sexual','shade','shadow','shake','shall','shape',
  'share','shared','sharp','she','sheet','shelf','shell','shelter','shift','shine',
  'ship','shirt','shit','shock','shoe','shoot','shooting','shop','shopping',
  'shore','short','shortly','shot','should','shoulder','shout','show','shower',
  'shrug','shut','sick','side','sight','sign','signal','significant',
  'significantly','silence','silent','silver','similar','similarity','simple',
  'simply','simultaneously','sin','since','sing','singer','single','sink','sir',
  'sister','sit','site','situation','six','size','ski','skill','skin','sky',
  'slave','sleep','slice','slide','slight','slightly','slip','slow','slowly',
  'small','smart','smell','smile','smoke','smooth','snap','snow','so','soak',
  'so-called','soccer','social','society','soft','software','soil','solar',
  'soldier','sole','solely','solid','solution','solve','some','somebody','somehow',
  'someone','something','sometimes','somewhat','son','song','soon','sophisticated',
  'sorry','sort','soul','sound','source','south','southern','space','span','speak',
  'speaker','special','specialist','species','specific','specifically','specify',
  'speech','speed','spell','spend','sphere','spin','spirit','spiritual','split',
  'spokesman','sponsor','sport','spot','spread','spring','square','squeeze',
  'stability','stable','staff','stage','stake','stand','standard','standing',
  'star','stare','start','state','statement','station','statistics','status',
  'stay','steady','steal','steel','step','stick','still','stimulus','stock',
  'stomach','stone','stop','storage','store','storm','story','straight','strange',
  'stranger','strategic','strategy','stream','street','strength','strengthen',
  'stress','stretch','strike','striking','string','strip','stroke','strong',
  'strongly','structure','struggle','student','studio','study','stuff','stumble',
  'style','subject','submit','subsequent','substance','substantial','succeed',
  'success','successful','successfully','such','sudden','suddenly','sue','suffer',
  'sufficient','sugar','suggest','suggestion','suicide','suit','sum','summarize',
  'summary','summer','summit','sun','super','superior','supply','support',
  'supporter','suppose','supposedly','supreme','sure','surely','surface','surgery',
  'surprise','surprised','surprising','surprisingly','surround','surveillance',
  'survey','survival','survive','survivor','suspect','suspend','suspicion',
  'suspicious','sustain','sustainable','symbol','symbolic','sympathy','symptom',
  'syndrome','synthetic','system','table','tackle','tail','take','tale','talent',
  'talented','talk','tall','tank','tap','tape','target','task','taste','tax',
  'taxpayer','tea','teach','teacher','teaching','team','tear','teaspoon','technical',
  'technique','technology','teenager','telephone','television','tell','temperature',
  'temple','temporary','ten','tend','tendency','tennis','tension','tent','term',
  'terms','terrain','terrible','territory','terror','terrorism','terrorist','test',
  'testify','testimony','testing','text','texture','than','thank','thanks','that',
  'the','theater','their','them','theme','themselves','then','theoretical','theory',
  'therapist','therapy','there','therefore','these','they','thick','thin','thing',
  'think','thinking','third','thirty','this','those','though','thought','thousand',
  'threat','threaten','three','throat','through','throughout','throw','thumb',
  'thus','ticket','tide','tie','tight','tighten','till','timber','time','timing',
  'tiny','tip','tire','tired','tissue','title','today','toe','together','tomorrow',
  'tone','tongue','tonight','tool','tooth','top','topic','toss','total','totally',
  'touch','tough','tour','tourism','tourist','tournament','toward','towards',
  'tower','town','toy','trace','track','trade','trademark','tradition','traditional',
  'traffic','tragedy','trail','train','training','transfer','transform',
  'transformation','transition','translate','transportation','trap','trash',
  'travel','treasure','treat','treatment','treaty','tree','tremendous','trend',
  'trial','triangle','tribe','trick','trigger','trim','trip','triumph','troop',
  'tropical','trouble','truck','true','truly','trust','truth','try','tube',
  'tuck','tune','tunnel','turn','tv','twelve','twenty','twice','twin','twist',
  'two','type','typical','typically','ugly','ultimate','ultimately','umbrella',
  'unable','unacceptable','unaware','uncertainty','uncle','uncomfortable',
  'unconscious','unconventional','under','undergo','undergraduate','undermine',
  'understand','understanding','underway','unemployment','unexpected','unfair',
  'unfold','unfortunate','unfortunately','unhappy','uniform','union','unique',
  'unit','unite','united','unity','universal','universe','university','unknown',
  'unless','unlike','unlikely','unprecedented','until','unusual','update','upon',
  'upper','upset','urban','urge','urgent','us','usage','use','useful','user',
  'usual','usually','utility','utilize','vaccine','vacuum','vague','valid',
  'valuable','value','valve','van','variable','variation','variety','various',
  'vary','vast','vector','vegetable','vehicle','venture','verbal','verdict',
  'version','versus','vertical','vessel','veteran','via','vice','victim','victory',
  'video','view','viewer','village','violate','violation','violence','violent',
  'virtually','virtue','virus','visible','vision','visit','visitor','visual',
  'vital','vitamin','voice','volume','voluntary','volunteer','vote','voter',
  'voting','vulnerable','wage','wait','wake','walk','wall','wander','want',
  'war','warm','warn','warning','warrant','wash','waste','watch','water','wave',
  'way','weak','weaken','weakness','wealth','wealthy','weapon','wear','weather',
  'web','wedding','week','weekend','weekly','weigh','weight','weird','welcome',
  'welfare','well','west','western','wet','whale','what','whatever','wheel',
  'when','whenever','where','whereas','wherever','whether','which','while',
  'whisper','white','whole','whom','whose','why','wide','widely','widespread',
  'wife','wild','wildlife','will','willing','win','wind','window','wine','wing',
  'winner','winter','wipe','wire','wisdom','wise','wish','with','withdraw',
  'within','without','witness','woman','wonder','wonderful','wood','wooden',
  'word','work','worker','working','workplace','works','workshop','world',
  'worldwide','worm','worried','worry','worse','worship','worst','worth','worthy',
  'would','wound','wrap','write','writer','writing','wrong','yard','year','yell',
  'yellow','yes','yesterday','yet','yield','you','young','your','yours',
  'yourself','youth','zone'
]);

// Also filter these common JS identifiers
for (const v of [
  'app','path','fs','__dirname','__dirname_route','execAsync','execFileAsync',
  'loadSessions','saveSessions','getAgentTraces','logAgentTrace','clearTraces',
  'hermesBridge','isAgentBusy','needsRestart','restartTimer','masterSocketId',
  'writeCrashLog','killPickFolderProcess','pickFolderInProgress','pickFolderChildPid',
  'pidMap','pidMapPath','computeGitChangesDelta','gitCommitJobs','godSocket',
  'activeProcesses','pendingDelegations','scanExternalHermesProcesses',
  'trackedHermesProcesses','loadCredentials','saveCredentials','getPlatforms',
  'publish','publishMultiple','getPlatformInfo','ensureOllamaRunning',
  'triggerRestart','ensureResumen','callHermesAdmin','callHermesAdminStreaming',
  'cleanupDeadBridgeInstances','extractTelegramSummary','getFileGitDiff',
  'getGitChangeSnapshot','saveLog','getLogs','loadLogs','_wsClients',
  'app','hermesBridge','execAsync','execFileAsync','writeCrashLog',
  'loadSessions','saveSessions','updateSessions','getAgentTraces','logAgentTrace',
  'clearTraces','http','WebSocket','cors','express','EventEmitter',
  'existsSync','readFileSync','mkdirSync','writeFileSync','appendFileSync',
  'readFile','writeFile','mkdir','access','readdir','stat','unlink','rename',
  'AgentGraph','stripAnsi','escapeMarkdownV2','formatMessage',
  'ToolProgressManager','SSEParser','HermesGatewayClient','formatProgressLines',
  'stripMarkdownV2','getToolEmoji','createRequire'])) {
  CLOSURE_VARS.add(v);
}

// Save closure vars
fs.writeFileSync('server/_deps.json', JSON.stringify([...CLOSURE_VARS].sort(), null, 2));
console.log(`Saved ${CLOSURE_VARS.size} dependency variables to server/_deps.json`);
